export const mockProfiles = [
  {
    id: '1',
    email: 'samuelklausfischer@hotmail.com',
    name: 'Samuel Fischer',
    perfil: 'administrador',
    ativo: true,
  },
  {
    id: '2',
    email: 'financeiro@empresa.com',
    name: 'Analista Financeiro',
    perfil: 'financeiro',
    ativo: true,
  },
  { id: '3', email: 'gestor@empresa.com', name: 'Gestor de Contas', perfil: 'gestor', ativo: true },
]

export const mockRecebedores = [
  {
    id: 'r1',
    nome_razao_social: 'Dr. João Silva',
    tipo: 'medico',
    cpf_cnpj: '111.222.333-44',
    email: 'joao@clinica.com',
    ativo: true,
  },
  {
    id: 'r2',
    nome_razao_social: 'TechMed Equipamentos',
    tipo: 'fornecedor',
    cpf_cnpj: '12.345.678/0001-90',
    email: 'vendas@techmed.com',
    ativo: true,
  },
  {
    id: 'r3',
    nome_razao_social: 'Limpeza e Cia',
    tipo: 'empresa',
    cpf_cnpj: '98.765.432/0001-10',
    email: 'contato@limpezacia.com',
    ativo: true,
  },
  {
    id: 'r4',
    nome_razao_social: 'Dra. Maria Souza',
    tipo: 'medico',
    cpf_cnpj: '555.666.777-88',
    email: 'maria@clinica.com',
    ativo: true,
  },
  {
    id: 'r5',
    nome_razao_social: 'Consultoria Contábil',
    tipo: 'empresa',
    cpf_cnpj: '11.222.333/0001-44',
    email: 'contato@contabil.com',
    ativo: false,
  },
]

const today = new Date()
const addDays = (d: number) => new Date(today.getTime() + d * 86400000).toISOString().split('T')[0]

export const mockPagamentos = [
  {
    id: 'p1',
    recebedor_id: 'r1',
    recebedores: mockRecebedores[0],
    descricao: 'Plantão Maio',
    valor: 3500.0,
    data_vencimento: addDays(-2),
    status: 'pago',
  },
  {
    id: 'p2',
    recebedor_id: 'r2',
    recebedores: mockRecebedores[1],
    descricao: 'Manutenção Raio-X',
    valor: 12500.0,
    data_vencimento: addDays(2),
    status: 'pendente',
  },
  {
    id: 'p3',
    recebedor_id: 'r3',
    recebedores: mockRecebedores[2],
    descricao: 'Serviços de Limpeza',
    valor: 4200.0,
    data_vencimento: addDays(5),
    status: 'em_conferencia',
  },
  {
    id: 'p4',
    recebedor_id: 'r4',
    recebedores: mockRecebedores[3],
    descricao: 'Cirurgia Ortopédica',
    valor: 8900.0,
    data_vencimento: addDays(1),
    status: 'com_alerta',
  },
  {
    id: 'p5',
    recebedor_id: 'r2',
    recebedores: mockRecebedores[1],
    descricao: 'Peças de Reposição',
    valor: 1500.0,
    data_vencimento: addDays(10),
    status: 'pendente',
  },
  {
    id: 'p6',
    recebedor_id: 'r1',
    recebedores: mockRecebedores[0],
    descricao: 'Plantão Junho',
    valor: 3500.0,
    data_vencimento: addDays(15),
    status: 'pendente',
  },
  {
    id: 'p7',
    recebedor_id: 'r5',
    recebedores: mockRecebedores[4],
    descricao: 'Auditoria Anual',
    valor: 6000.0,
    data_vencimento: addDays(-10),
    status: 'pago',
  },
  {
    id: 'p8',
    recebedor_id: 'r3',
    recebedores: mockRecebedores[2],
    descricao: 'Material de Limpeza',
    valor: 850.0,
    data_vencimento: addDays(3),
    status: 'aprovado',
  },
  {
    id: 'p9',
    recebedor_id: 'r4',
    recebedores: mockRecebedores[3],
    descricao: 'Consulta Especialista',
    valor: 450.0,
    data_vencimento: addDays(-1),
    status: 'cancelado',
  },
  {
    id: 'p10',
    recebedor_id: 'r2',
    recebedores: mockRecebedores[1],
    descricao: 'Atualização de Software',
    valor: 2100.0,
    data_vencimento: addDays(4),
    status: 'com_alerta',
  },
]

export const mockAlertas = [
  {
    id: 'a1',
    pagamento_id: 'p4',
    pagamentos: mockPagamentos[3],
    tipo: 'valor_suspeito',
    descricao: 'Valor 30% acima da média para este recebedor',
    revisado: false,
  },
  {
    id: 'a2',
    pagamento_id: 'p10',
    pagamentos: mockPagamentos[9],
    tipo: 'duplicidade',
    descricao: 'Possível pagamento em duplicidade com fatura #4521',
    revisado: false,
  },
  {
    id: 'a3',
    pagamento_id: 'p2',
    pagamentos: mockPagamentos[1],
    tipo: 'vencimento_proximo',
    descricao: 'Vencimento em menos de 48h',
    revisado: true,
  },
  {
    id: 'a4',
    pagamento_id: 'p5',
    pagamentos: mockPagamentos[4],
    tipo: 'campo_faltando',
    descricao: 'Nota fiscal não anexada',
    revisado: false,
  },
  {
    id: 'a5',
    pagamento_id: 'p6',
    pagamentos: mockPagamentos[5],
    tipo: 'cadastro_incompleto',
    descricao: 'Dados bancários do recebedor desatualizados',
    revisado: false,
  },
]
